# Generated by Django 4.2.6 on 2023-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='passwrd',
            field=models.CharField(default='a', max_length=26),
            preserve_default=False,
        ),
    ]
