# Generated by Django 4.2.6 on 2023-10-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_user_address_user_passwrd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwrd',
        ),
    ]
