# Generated by Django 4.2.6 on 2023-10-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_user_passwrd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
