# Generated by Django 4.2.6 on 2023-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_user_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_price', models.CharField(max_length=20, null=True)),
                ('product_image', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
