# Generated by Django 4.2.6 on 2023-11-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
