# Generated by Django 4.2.6 on 2023-11-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_addproduct_product_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addproduct',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='quantity',
        ),
    ]
