# Generated by Django 4.2.6 on 2023-12-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
